import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { cancel, intro, isCancel, note, outro, select } from '@clack/prompts'
import {
  type LyraNetwork,
  agentPaths,
  defineConfig,
  placeholderAgentId,
  suiRpcUrl,
} from 'lyra-core'
import { writeConfigTs } from '../config/render'
import { AGENT_KEY_ENV, loadAgentFromEnv } from '../util/sui-runtime'
import { pickBrainModel } from './init/model-picker'

/**
 * `lyra init` — bootstrap the agent config for Sui.
 *
 * On Sui there is no operator wallet, keystore, or funding step. The agent IS
 * the signer: one Ed25519 keypair, supplied via the `LYRA_AGENT_KEY` env var
 * (`suiprivkey1…`). init resolves that key, derives the agent's Sui address,
 * writes `~/.lyra/config.ts`, and seeds the starter memory files.
 */
export async function runInit(opts?: { resume?: boolean }): Promise<void> {
  const configPath = agentPaths.config

  intro('lyra init')

  if (existsSync(configPath) && !opts?.resume) {
    const choice = (await select({
      message: `${configPath} exists`,
      options: [
        { value: 'overwrite', label: 'Start fresh (overwrite)' },
        { value: 'cancel', label: 'Cancel' },
      ],
      initialValue: 'cancel',
    })) as 'overwrite' | 'cancel' | symbol
    if (isCancel(choice) || choice === 'cancel') {
      cancel('Aborted.')
      return
    }
  }

  // The agent key is sourced from the environment (never prompted/stored on
  // disk). If it is missing we cannot derive the Sui address, so bail with a
  // clear instruction.
  const agent = loadAgentFromEnv()
  if (!agent) {
    cancel(
      `No ${AGENT_KEY_ENV} set. Export your agent's Sui secret key first, e.g.\n  export ${AGENT_KEY_ENV}=suiprivkey1...\nThen re-run \`lyra init\`.`,
    )
    return
  }

  const network = (await select({
    message: 'Which Sui network?',
    options: [
      { value: 'mainnet' as LyraNetwork, label: 'Sui mainnet' },
      { value: 'testnet' as LyraNetwork, label: 'Sui testnet' },
    ],
    initialValue: 'mainnet' as LyraNetwork,
  })) as LyraNetwork
  if (isCancel(network)) {
    cancel('Aborted.')
    return
  }

  const modelPick = await pickBrainModel()

  const agentId = placeholderAgentId(agent.address)
  const paths = agentPaths.agent(agentId)
  await mkdir(paths.dir, { recursive: true })

  // Telegram is env-driven on Sui (TELEGRAM_BOT_TOKEN). Auto-enable the plugin
  // when the token is present so `lyra` brings the DM gateway online.
  const telegramEnabled = !!process.env.TELEGRAM_BOT_TOKEN

  await seedStarterMemoryFiles({
    paths,
    network,
    agentAddress: agent.address,
    brainProvider: modelPick?.provider ?? null,
    brainModel: modelPick?.model ?? null,
  })

  const cfg = defineConfig({
    identity: {
      operator: null,
      agent: agent.address,
    },
    network,
    storage: { network },
    brain: {
      provider: modelPick?.provider ?? null,
      model: modelPick?.model ?? null,
    },
    plugins: telegramEnabled ? ['onchain', 'system', 'telegram'] : ['onchain', 'system'],
    tools: {},
    imports: { claudeCode: true },
  })
  await writeConfigTs(configPath, cfg, {
    header: '// Regenerated by `lyra init`. Edit freely; type-safe.',
  })

  const packageId = process.env.LYRA_PACKAGE_ID
  const lines = [
    '',
    `  agent id    ${agentId}`,
    `  agent addr  ${agent.address}`,
    `  network     ${network} (${suiRpcUrl(network)})`,
    `  config      ${configPath}`,
    `  policy pkg  ${packageId ?? '(set LYRA_PACKAGE_ID for on-chain receipts)'}`,
  ]
  if (modelPick) lines.push(`  brain       ${modelPick.model ?? '?'} (${modelPick.provider})`)
  if (telegramEnabled) lines.push('  telegram    enabled (TELEGRAM_BOT_TOKEN set)')
  lines.push(
    '',
    'Next: `lyra` to chat · `lyra status` for health · `lyra demo` for the guarded pipeline',
  )
  outro(lines.join('\n'))
}

interface SeedStarterOpts {
  paths: ReturnType<typeof agentPaths.agent>
  network: LyraNetwork
  agentAddress: string
  brainProvider: string | null
  brainModel: string | null
}

/**
 * Seed `MEMORY.md`, `/agent/identity.md`, and `/agent/persona.md` so the
 * brain's first turn sees a parseable memory index and introduces itself.
 */
async function seedStarterMemoryFiles(opts: SeedStarterOpts): Promise<void> {
  const memDir = opts.paths.memoryDir
  const agentMem = `${memDir}/agent`
  const userMem = `${memDir}/user`
  await mkdir(agentMem, { recursive: true })
  await mkdir(userMem, { recursive: true })

  const now = new Date().toISOString().slice(0, 10)
  const identity = `---\nname: identity\ndescription: Auto-written agent identity facts.\ntype: agent-identity\n---\n# Lyra identity\n\n- Name: Lyra\n- Agent address: ${opts.agentAddress} (${opts.network})\n- Created: ${now}\n${opts.brainProvider ? `- Brain provider: ${opts.brainProvider}\n` : ''}${opts.brainModel ? `- Brain model: ${opts.brainModel}\n` : ''}`
  const persona = `---\nname: persona\ndescription: Voice + behavior style.\ntype: agent-persona\n---\n# Persona\n\nI am Lyra, a Sui-native autonomous finance agent. I convert goals into policy-checked PTBs, execute only within my approved protocol scope, and store auditable memory and receipts with Walrus. Every value-moving action is checked by a deterministic policy (mirrored on-chain by lyra::policy) before it runs. I am direct, concise, and factual.\n`
  const profile =
    '---\nname: profile\ndescription: User profile (local only).\ntype: user\n---\n# User profile\n\n(empty, fills as we chat)\n'

  await writeFile(join(agentMem, 'identity.md'), identity, 'utf8')
  await writeFile(join(agentMem, 'persona.md'), persona, 'utf8')
  await writeFile(join(userMem, 'profile.md'), profile, 'utf8')
  await writeFile(opts.paths.memoryIndex, '# Lyra Memory Index\n\n', 'utf8')
}
