import { describe, expect, test } from 'bun:test'
import { Ed25519Keypair } from '@mysten/sui/keypairs/ed25519'
import { encryptToPubkey, generateBootstrapKeypair } from 'lyra-core'
import {
  type ProvisionRequest,
  adminTickDigest,
  approvalResponseDigest,
  chatMessageDigest,
  provisionMessageDigest,
  verifyAdminTickSig,
  verifyApprovalSig,
  verifyChatSig,
  verifyProvisionSig,
} from './auth'
import type { Hex } from './operator-sig'
import type { RuntimeConfig } from './runtime'

const INFT_REF = { contract: '0x9e71d79f06f956d4d2666b5c93dafab721c84721', tokenId: '6' } as const

const CONFIG: RuntimeConfig = {
  network: 'mainnet',
  brain: { provider: 'openai', model: 'gpt-4o-mini' },
  identity: {
    agent: `0x${'11'.repeat(32)}`,
  },
}

// The operator authenticates remote (sandbox) requests with a Sui Ed25519 key.
// Tests sign the digest as a Sui personal message; the production verifier in
// ./auth checks the recovered signer address via `verifyPersonalMessageSignature`.
async function sign(operator: Ed25519Keypair, digest: Uint8Array): Promise<string> {
  const { signature } = await operator.signPersonalMessage(digest)
  return signature
}

function makeRequest(): { req: ProvisionRequest; bootstrapPub: Hex } {
  const bootstrap = generateBootstrapKeypair()
  // Encrypt a 32-byte agent seed so the envelope round-trips like production.
  const agentSeed = new Uint8Array(32)
  crypto.getRandomValues(agentSeed)
  const envelope = encryptToPubkey({
    recipientPubkey: bootstrap.pubkeyHexCompressed,
    plaintext: agentSeed,
  })
  return {
    req: {
      envelope,
      operatorAddress: '0x0000000000000000000000000000000000000000000000000000000000000000',
      iNFTRef: INFT_REF,
      config: CONFIG,
      ts: Date.now(),
    },
    bootstrapPub: bootstrap.pubkeyHexCompressed,
  }
}

describe('provision sig verification', () => {
  test('roundtrip: operator signs the digest, harness verifies', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress()
    req.operatorAddress = operatorAddress as `0x${string}`

    const digest = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(operator, digest)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: operatorAddress as `0x${string}`,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects when operatorAddress does not match expectedOperator', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    const wrongOperator = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`

    const digest = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(operator, digest)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: wrongOperator.toSuiAddress() as `0x${string}`,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('operator-mismatch')
  })

  test('rejects when signature was generated by a different key', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    const attacker = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`

    const digest = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(attacker, digest)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('sig-mismatch')
  })

  test('rejects sig over a different bootstrap pubkey (replay-against-other-harness)', async () => {
    const { req } = makeRequest()
    const operator = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`

    const otherGatewayPub = generateBootstrapKeypair().pubkeyHexCompressed
    const realGatewayPub = generateBootstrapKeypair().pubkeyHexCompressed

    const digestForOther = provisionMessageDigest(req, otherGatewayPub)
    const sig = await sign(operator, digestForOther)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: realGatewayPub,
      expectedOperator: req.operatorAddress,
    })
    // A signature over a *different* digest fails Sui ed25519 verification
    // against the reconstructed message → sig-decode (vs a recover-then-
    // compare scheme's 'sig-mismatch'). Either way: rejected.
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toMatch(/^sig-decode/)
  })

  test('rejects sig if config mutated between sign and verify', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`
    const digest = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(operator, digest)
    // Tamper with config after signing.
    req.config = { ...req.config, brain: { ...req.config.brain, model: 'evil-model' } }
    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    // Tampered config → reconstructed digest differs from the signed one, so
    // the ed25519 signature no longer verifies. Rejected as sig-decode.
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toMatch(/^sig-decode/)
  })

  test('rejects stale ts', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`
    const now = 1_000_000_000_000
    req.ts = now - 10 * 60 * 1000

    const digest = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(operator, digest)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
      now,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('ts-stale')
  })

  test('rejects ts too far in the future', async () => {
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`
    const now = 1_000_000_000_000
    req.ts = now + 5 * 60 * 1000

    const digest = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(operator, digest)

    const r = await verifyProvisionSig({
      request: req,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
      now,
    })
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.reason).toBe('ts-future')
  })

  test('survives JSON.stringify→parse roundtrip when config carries undefined-valued optional fields', async () => {
    // Regression: CLI builds RuntimeConfig with `promptAppend: undefined`
    // (caller didn't set it). It signs the in-memory config, JSON.stringify
    // drops the field on the wire, and the harness's parsed config has no
    // `promptAppend` key. If `stableStringify` hashed `undefined` as the
    // literal text "undefined" for the CLI but skipped the key for the
    // harness, the digests would differ.
    const { req, bootstrapPub } = makeRequest()
    const operator = Ed25519Keypair.generate()
    req.operatorAddress = operator.toSuiAddress() as `0x${string}`
    req.config = {
      ...req.config,
      // biome-ignore lint/suspicious/noExplicitAny: deliberately exercising the optional-undefined path
      promptAppend: undefined as any,
      // biome-ignore lint/suspicious/noExplicitAny: same
      plugins: undefined as any,
    }
    const digestCli = provisionMessageDigest(req, bootstrapPub)
    const sig = await sign(operator, digestCli)

    // Simulate the wire roundtrip the harness sees.
    const reqOnWire = JSON.parse(JSON.stringify(req)) as ProvisionRequest
    expect((reqOnWire.config as unknown as Record<string, unknown>).promptAppend).toBeUndefined()
    expect(Object.hasOwn(reqOnWire.config, 'promptAppend')).toBe(false)

    const r = await verifyProvisionSig({
      request: reqOnWire,
      signature: sig,
      bootstrapPubkey: bootstrapPub,
      expectedOperator: req.operatorAddress,
    })
    expect(r.ok).toBe(true)
  })
})

describe('chat sig verification', () => {
  test('roundtrip', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const digest = chatMessageDigest('hello', ts, 'sbx-1')
    const sig = await sign(operator, digest)
    const r = await verifyChatSig({
      message: 'hello',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects signature from a different sandbox', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const sigForOther = await sign(operator, chatMessageDigest('hello', ts, 'sbx-other'))
    const r = await verifyChatSig({
      message: 'hello',
      ts,
      sandboxId: 'sbx-real',
      signature: sigForOther,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(false)
  })
})

describe('admin tick sig verification', () => {
  test('roundtrip for autotopup-tick action', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const digest = adminTickDigest({ action: 'autotopup-tick', ts, sandboxId: 'sbx-enigma' })
    const sig = await sign(operator, digest)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-enigma',
      signature: sig,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects sig for a different action (cross-action replay)', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const sigForOther = await sign(
      operator,
      adminTickDigest({ action: 'sync-trigger', ts, sandboxId: 'sbx-1' }),
    )
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sigForOther,
      expectedOperator: operatorAddress,
    })
    // Sig made over a different action digest → fails ed25519 verification
    // against the reconstructed 'autotopup-tick' digest. Rejected as sig-decode.
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toMatch(/^sig-decode/)
  })

  test('rejects sig for a different sandbox', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const sigForOther = await sign(
      operator,
      adminTickDigest({ action: 'autotopup-tick', ts, sandboxId: 'sbx-other' }),
    )
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-real',
      signature: sigForOther,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(false)
  })

  test('rejects expired ts (>5 min stale)', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now() - 6 * 60 * 1000
    const digest = adminTickDigest({ action: 'autotopup-tick', ts, sandboxId: 'sbx-1' })
    const sig = await sign(operator, digest)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('ts-stale')
  })

  test('rejects future-skewed ts (>1 min ahead)', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now() + 2 * 60 * 1000
    const digest = adminTickDigest({ action: 'autotopup-tick', ts, sandboxId: 'sbx-1' })
    const sig = await sign(operator, digest)
    const r = await verifyAdminTickSig({
      action: 'autotopup-tick',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(false)
    if (r.ok) throw new Error('unreachable')
    expect(r.reason).toBe('ts-future')
  })
})

describe('approval sig verification', () => {
  test('roundtrip', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const digest = approvalResponseDigest({
      approvalId: 'apv-1',
      decision: 'allow',
      ts,
      sandboxId: 'sbx-1',
    })
    const sig = await sign(operator, digest)
    const r = await verifyApprovalSig({
      approvalId: 'apv-1',
      decision: 'allow',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(true)
  })

  test('rejects mismatched decision', async () => {
    const operator = Ed25519Keypair.generate()
    const operatorAddress = operator.toSuiAddress() as `0x${string}`
    const ts = Date.now()
    const sig = await sign(
      operator,
      approvalResponseDigest({ approvalId: 'apv-1', decision: 'allow', ts, sandboxId: 'sbx-1' }),
    )
    const r = await verifyApprovalSig({
      approvalId: 'apv-1',
      decision: 'deny',
      ts,
      sandboxId: 'sbx-1',
      signature: sig,
      expectedOperator: operatorAddress,
    })
    expect(r.ok).toBe(false)
  })
})
